### ISSUE TITLE
UpgradeException

### ISSUE THREAD

**Issue by Quillbert** [alexandrainst/processing_websockets#16]
When trying to connect to socket.io apps hosted on certain websites, I get this error:
`UpgradeException: Didn't switch protocols, expected status <101>, but got <301>`
Any idea what that means, or how to fix it?

**Comment by hamoid** [comment]
Here more details about the error:

https://discourse.processing.org/t/processing-to-socket-io-on-unubo/9182

One place to test it is this: https://www.websocket.org/echo.html
By testing the websocketClient with that server it shows this error:

```
onError(IOException: Cannot init SSL)
java.io.IOException: Cannot init SSL
	at org.eclipse.jetty.websocket.client.io.WebSocketClientSelectorManager.newConnection(WebSocketClientSelectorManager.java:98)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:411)
	at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:56)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:587)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101)
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

To enable SSL:

```
SslContextFactory ssl = new SslContextFactory();
// Configure ssl for your client here, such as
// what ciphers and protocols are available,
// what client certificates to use,
// what CA's you want to validate against,
// what your blacklist behavior is,
// your truststore location and access,
// your keystore location and access,
// caching, CRL, OCSP, renegotiation, etc ...

WebSocketClient client = new WebSocketClient(ssl);
```

Found at https://stackoverflow.com/a/29759341
