### ISSUE TITLE
NoSuchMethodError on older android device (Processing for android)

### ISSUE THREAD

**Issue by EqAnom** [alexandrainst/processing_websockets#28]
Hello, I am trying to run this websocket library for processing for android on a Samsung Galaxy Tab 4 (Android ver. 5.02) and its giving me an error I cant seem to resolve:

```
java.lang.NoSuchMethodError: No virtual method getRemoteAddress()Ljava/net/SocketAddress; in class Ljava/nio/channels/SocketChannel; or its super classes (declaration of 'java.nio.channels.SocketChannel' appears in /system/framework/core-libart.jar)
	at org.eclipse.jetty.io.SelectorManager.chooseSelector(SelectorManager.java:148)
	at org.eclipse.jetty.io.SelectorManager.connect(SelectorManager.java:189)
	at org.eclipse.jetty.websocket.client.io.ConnectionManager$PhysicalConnect.run(ConnectionManager.java:76)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:818)
WebSocket Client API Error: (NoSuchMethodError: No virtual method getRemoteAddress()Ljava/net/SocketAddress; in class Ljava/nio/channels/SocketChannel; or its super classes (declaration of 'java.nio.channels.SocketChannel' appears in /system/framework/core-libart.jar))
```

Ive used the library on my Samsung Galaxy S9 with no issues. It only seems to happen on this tablet. Is there any way around this?

**Comment by EqAnom** [comment]
Error solved by upgrading device to Android 11
