### ISSUE TITLE
wss:// SSL support?

### ISSUE THREAD

**Issue by efstajas** [alexandrainst/processing_websockets#5]
I've been using this library for quite a while without issues, but recently I had to change my server's configuration over to SSL, and I cannot get it to connect. I changed my URL in processing to wss://, but all I get is this error:

```
onError(IOException: Cannot init SSL)
java.io.IOException: Cannot init SSL
	at org.eclipse.jetty.websocket.client.io.WebSocketClientSelectorManager.newConnection(WebSocketClientSelectorManager.java:98)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:411)
	at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:56)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:587)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101)
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
onError(IOException: Cannot init SSL)
java.io.IOException: Cannot init SSL
	at org.eclipse.jetty.websocket.client.io.WebSocketClientSelectorManager.newConnection(WebSocketClientSelectorManager.java:98)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:411)
	at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:56)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:587)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101)
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

```

I read something about passing an SSLContextFactory object in place of the URL, but from what I've seen in the source code for this library it won't accept anything other than a PApplet and an URL String.

Is there a way to connect using SSL, and if not, could you point me into the right direction for modifying it myself?

**Comment by Baddaboo** [comment]
Any update on this? Almost all web services force SSL and most WebSocket implementations enable SSL by default. Without any fix or workaround, this library is essentially useless

**Comment by q2dg** [comment]
Well, last commit was three years ago. Sadly, this project seems abandoned. It's a pity

**Comment by hamoid** [comment]
Basic support for SSL was added yesterday. Maybe you can give it a try see if it works for you.

**Comment by efstajas** [comment]
@hamoid cheers man! would like to check, but unfortunately moved on from this project a long time ago — huge kudos for getting this fixed though!

**Comment by dattasaurabh82** [comment]
Any supporting example for the ssl ?

**Comment by hamoid** [comment]
@dattasaurabh82 Looking at https://github.com/alexandrainst/processing_websockets/commit/73f08bf7e20c83b84ca995f7a91a097a42d2fb79 (which I seem to have written myself) the only thing to do is to use a URI that starts with `wss`. Does that help?

**Comment by dattasaurabh82** [comment]
> @dattasaurabh82 Looking at [73f08bf](https://github.com/alexandrainst/processing_websockets/commit/73f08bf7e20c83b84ca995f7a91a097a42d2fb79) (which I seem to have written myself) the only thing to do is to use a URI that starts with `wss`. Does that help?

Got it. Will give it a try. 
I was just wondering if some cert files need to be introduced here or something. Will try it tomorrow ASAP

**Comment by Alkarex** [comment]
By the way @hamoid , https://github.com/alexandrainst/processing_websockets/issues/27 ;-)

**Comment by hamoid** [comment]
Also looking for someone to maintain https://github.com/hamoid/video_export_processing :-) I switched to OPENRNDR in 2020 and I put my contributing energies into it :-)

**Comment by dattasaurabh82** [comment]
> @dattasaurabh82 Looking at [73f08bf](https://github.com/alexandrainst/processing_websockets/commit/73f08bf7e20c83b84ca995f7a91a097a42d2fb79) (which I seem to have written myself) the only thing to do is to use a URI that starts with `wss`. Does that help?

Sorry for replying in this thread late. 
Below is my sketch (a very simple implementation to just test):

```Processing
import websockets.*;

WebsocketClient wsc;
int now;
boolean newEllipse;

void setup() {
    size(200, 200);

    newEllipse=true;

    wsc= new WebsocketClient(this, "wss://localhost:8766/john");
    now=millis();
}

void draw() {
    if (newEllipse) {
        ellipse(random(width), random(height), 10, 10);
        newEllipse=false;
    }

    if (millis()>now+5000) {
        wsc.sendMessage("Client message");
        now=millis();
    }
}

void webSocketEvent(String msg) {
    println(msg);
    newEllipse=true;
}
```

In the above example, the port and the header is fine. 
I'm running a simple Python Websocket Server with my own ssl keys:

```Python
import asyncio
import ssl
import websockets
import logging


async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)


def main():
    # Configure logging
    logging.basicConfig(level=logging.INFO)

    # SSL context setup for Secure WebSocket (wss://)
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ssl_context.load_cert_chain('certificate.pem', 'key.pem')

    # Create a new event loop and set it as the current one
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    # Define the WebSocket server (ws://)
    start_server_ws = websockets.serve(echo, "localhost", 8765)
    loop.run_until_complete(start_server_ws)
    logging.info("WebSocket server started on ws://localhost:8765")
    
    # Define the Secure WebSocket server (wss://)
    start_server_wss = websockets.serve(echo,
                                        "localhost", 8766, ssl=ssl_context)
    loop.run_until_complete(start_server_wss)
    logging.info("Secure WebSocket server started on wss://localhost:8766")

    # Start and run the servers
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        pass
    finally:
        loop.close()
        logging.info("WebSocket servers stopped.")


if __name__ == "__main__":
    main()
```

The server seems to run fine and can connect to the above client over non-ssl port, just fine. 
But simply replacing `ws://` with `wss://` just hangs the sketch; the applet window loads, but doesn't nothing happens.

**Comment by hamoid** [comment]
I would set https://github.com/alexandrainst/processing_websockets/blob/master/src/websockets/WebsocketServer.java#L21 to true, build the websockets library, then try again. Logging is disabled by default.

**Comment by hamoid** [comment]
Ah I see you can call this method to turn debug on: https://github.com/alexandrainst/processing_websockets/blob/master/src/websockets/WebsocketServer.java#L136

It's even on the readme :-)
https://github.com/alexandrainst/processing_websockets?tab=readme-ov-file#enable-logging

**Comment by dattasaurabh82** [comment]
> Ah I see you can call this method to turn debug on: https://github.com/alexandrainst/processing_websockets/blob/master/src/websockets/WebsocketServer.java#L136
> 
> It's even on the readme :-) https://github.com/alexandrainst/processing_websockets?tab=readme-ov-file#enable-logging

But that's for server and not client. 
I'm running processing sketch as a client not a server. 
And, if I do `WebsocketServer.enableDebug();` within `setup()` before creating the client instance, it's show squiggly line. The function enableDebug() wasn't compiled? Weird! 
![Screenshot 2024-04-24 at 17 41 21](https://github.com/alexandrainst/processing_websockets/assets/4619862/75e72151-6af6-4ffd-9422-429302dd12fe)

**Comment by hamoid** [comment]
I hope someone else can take a look, too busy right now... Ideally the project would be ported to use Gradle so it would be easier for anyone to build the library. Currently there's no build instructions. I think I used "build artifact" in Idea.
