### ISSUE TITLE
Can't handle connection refused

### ISSUE THREAD

**Issue by orgicus** [alexandrainst/processing_websockets#6]
Hi,

I've just started using the library and wanted to have a sketch retry to connect every 5 seconds if the server isn't up. The problem is I can't seem get this to work.

I've tried creating a new ```WebsocketClient``` instance within a ```try...catch``` block, but no exception are thrown. They might be handled internally. The main problem is the sketch hangs:

```java
[Animation Thread] INFO org.eclipse.jetty.util.log - Logging initialized @1543ms
onError(ConnectException: Connection refused)
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:337)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:341)
	at org.eclipse.jetty.io.ManagedSelector.access$900(ManagedSelector.java:56)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:278)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:170)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:162)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.execute(ExecuteProduceConsume.java:101)
	at org.eclipse.jetty.io.ManagedSelector.run(ManagedSelector.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

What's the best approach for this situation ?

Thank you,
George

**Comment by orgicus** [comment]
I had much better luck using this java websocket library:
https://github.com/TakahikoKawasaki/nv-websocket-client

**Comment by jshaw** [comment]
@orgicus thanks so much, that library you suggested is such a good ref. and does much better error handling. 

Others might find this useful too -- I was having some trouble connecting to my Node.js webSocket from the docs in the nv-websocket-client library but found a good resource with some good examples that I was able to reference for syntax and structure for integrating into the Processing  environment and work correctly -- [https://www.programcreek.com/java-api-examples/?api=com.neovisionaries.ws.client.WebSocket](https://www.programcreek.com/java-api-examples/?api=com.neovisionaries.ws.client.WebSocket)

**Comment by botherder** [comment]
I am actually having the exact same issue while working on #20.
I've even tried to create a custom event to handle the onError events, but I don't seem to be having much success.
Anyone managed to resolve this issue other than switching libraries? If not, would you have examples to share on how you implemented that other library in Processing?

**Comment by botherder** [comment]
I have been having the same issue as I've been describing in #20.
I try to handle `onError` with a method in the sketch, but the sketch hangs:
https://github.com/botherder/processing_websockets

Anyone found a solution? If not, would you have examples to share on how you used this other library in Processing?

**Comment by botherder** [comment]
Apparently it's the `latch.await()` causing it to hang in case a connection fails. It seems like there isn't proper exception handling in some of the upstream dependencies.
